### ISSUE TITLE
full-setup: Emacs 30.2 fails to build against tree-sitter >= 0.25

### ISSUE THREAD

**Issue by jlipworth** [jlipworth/devenv#71]
On a fresh Arch box (jl-omarchy01, Omarchy 4.0.1, 2026-08-28), `make full-setup` fails in the spacemacs target: emacs-30.2 src/treesit.c:749 — "implicit declaration of function 'ts_language_version'; did you mean 'ts_language_abi_version'" (tree-sitter >= 0.25 renamed the API). Chain: makefile:39 'spacemacs' -> makefile:197 'full-setup'. Everything after the spacemacs target never ran. Likely fixes: bump the pinned Emacs to a release supporting tree-sitter 0.25, or apply the upstream compat patch pre-build. A diagnosis pass is also checking whether linuxbrew was the intended toolchain on Arch (R packages were compiling under /home/linuxbrew before the failure) or whether DISTRO detection misfired — findings will be added as a comment. Build log preserved at /tmp/devenv-full-setup.log on jl-omarchy01.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by jlipworth** [comment]
Diagnosis (read-only pass over the full 8,396-line build log on jl-omarchy01 + the repo):

**Confirmed: the Emacs 30.2 / tree-sitter ≥ 0.25 ABI rename — but it's a devenv guard gap, not a distro quirk.** devenv already ships the fix: build_emacs30.sh exports `-Dts_language_version=ts_language_abi_version` when tree-sitter ≥ 0.25 is detected — **but only in the Linuxbrew (lines ~140-143) and macOS (~295-298) branches**, because the check is keyed on `brew list --versions tree-sitter`. The Arch branch (~72-105, pacman tree-sitter, VM has 0.26.9-1) and the Debian apt sub-branch (~244-252) have no guard at all, so the compat define never fired ("Using tree-sitter 0.25+ compatibility define" never appears in the log). Introduced in a75f22a/dab53d8, never backported to the distro-package paths. Debian trixie will hit the identical wall.

**Everything else in the run was clean** — zero [ERROR] lines; DISTRO detection was correct (Arch branches ran throughout); Linuxbrew on Arch is *by design* (install_homebrew gates only on Linux, no DISTRO check), which also makes the Arch R branch at prereq_packages.sh:785 dead code (brew always wins the `is_installed brew` test first — R 4.6.1 + ~20 packages compiled under linuxbrew instead). The failure is the **last** target of full-setup, so only the tail of build_emacs30.sh was lost: `make install` to ~/.local, the Spacemacs clone (develop), and all-the-icons fonts. neovim 0.12.0, python-env, and all 20 prereq layers completed.

**Fix options, in order of value:**
1. Make the guard version-source-agnostic and unconditional: detect via `pkg-config --modversion tree-sitter` once, after all per-distro dependency branches, before configure — closes Arch, apt, and future distros in one edit and deletes the duplicated logic.
2. Bump EMACS_VERSION off 30.2 — the rename is fixed upstream in 30.3/31 (Arch extra ships emacs/emacs-wayland 31.1-1); retires the shim entirely. Verify Spacemacs develop against 31 first.
3. Consider an Arch fast path: there is no native-package Emacs path anywhere in prereq_packages.sh — `pacman -S emacs-wayland` would replace a 20-40 min source build and make this failure class structurally impossible on Arch.

**Adjacent items worth their own issues** (neither caused this): the dead Arch R branch (785, shadowed by brew), and the python → python-env ordering that makes the Jupyter install warn-and-skip on first run.

Minimal same-day fix if wanted: replicate the 3-line CPPFLAGS export into the Arch branch sourcing the version from `pacman -Q tree-sitter`.
